### ISSUE TITLE
Device Control, Signal Input/Output' in library rc-switch is not valid

### ISSUE THREAD

**Issue by mikekgr** [sui77/rc-switch#100]
Dear Sirs,
in the latest update of this library (2.6.0) I started to get the following warning:

WARNING: Category 'Device Control, Signal Input/Output' in library rc-switch is not valid. Setting to 'Uncategorized'

Do you know why, what is going wrong?

My setup is: Windows 7 64Bit, Arduino IDE 1.6.9

Thanks and best Regards,
Mike Kranidis

**Comment by aafent** [comment]
I have the same, but It is working perfect without any problem.

**Comment by icetee** [comment]
I have the same.

**Comment by sui77** [comment]
the category definition for the arduino library manager contained two categories but obviously only supports one.

should be fixed with 2.6.1
