### ISSUE TITLE
unsigned long code = mySwitch.getReceivedValue(); not reliable???

### ISSUE THREAD

**Issue by bartrouw** [sui77/rc-switch#119]
Hi there,

Not sure if this is the right place for this question. Maybe I do something wrong.
However: Once in every while it seams that mySwitch.getReceivedValue(); does not copy its value into the variable code (unsigned long) correctly.
I send code with codesend utility (unmodified, except for the pin number) from [ninjablocks](https://github.com/ninjablocks/433Utils)
```
pi@raspberrypi:~/433Utils/RPi_utils$ for ((i=0; i<100; i++)) do sudo ./codesend 9109515; done
[sudo] password for pi: 
sending code[9109515]
```

I receive it with modified RF_Sniffer on arduino.
Part of it:
```C
unsigned long code=0;

void loop() {
  
  if (mySwitch.available()) {
    
    code = mySwitch.getReceivedValue();
 
    if (code < 0) {
     // Serial.print("Unknown encoding");
    } else {
      Serial.print("Received: ");
      Serial.print( mySwitch.getReceivedValue() );
      Serial.print("; code: ");
      Serial.println( code ); 
    }
    mySwitch.resetAvailable();
  }
}
```

It just prints mySwitch.getReceivedValue() and code.
What I see is the following:
```
Received: 9109515; code: 9109504 <--
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109504 <--
Received: 9109515; code: 9109504 <--
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
Received: 9109515; code: 9109515
```

After further inverstigation it seems that when I split code into 16bit lower part and a 8bits upper part, the 16 bits lower part isn't copied into code.

My solution is to declare `RCSwitch::nReceivedValue` volatile in both the header as the cpp file. After that it works fine.

**Comment by fingolfin** [comment]
Change is f820d2e46ab227ac800960b57cdefc8f912006c6
