### ISSUE TITLE
350Mhz

### ISSUE THREAD

**Issue by SteveAbb** [sui77/rc-switch#140]
Is it possible to use this library to transmit over 350Mhz instead of 315/433?

**Comment by Martin-Laclaustra** [comment]
Any frequency. It depends only on the [SAW resonator](http://www.ienk.com/oscillators-saw-resonator-c-6_70.html) frequency of your [transmitter](https://www.sparkfun.com/products/10534).
You can transmit a code ([line code](https://en.wikipedia.org/wiki/Line_code)) in which every bit has a high and low part, and the different timings between those parts mark the logical value of the bits.
