### ISSUE TITLE
How does your library distinguish between a low signal and a high signal?

### ISSUE THREAD

**Issue by SamDecrock** [sui77/rc-switch#141]
Hello,

Thanks for your cool library, it really helps me in learning these 433Mhz protocols.

I began reading your library and I can't seem to figure out how you distinguish between an incoming low signal and an incoming high signal.

As I understand it `handleInterrupt()` gets called when the signal changes from low to high or from high to low. But I never see you querying the pin. So how can you know a message started with a high or a low signal? Or do you just assume the signal is always low until a new message comes in?

Thanks!
Sam

**Comment by Martin-Laclaustra** [comment]
Currently, master branch is not aware of that.
You can check the [protocollessreceiver branch](https://github.com/Martin-Laclaustra/rc-switch/tree/protocollessreceiver) for a code that stores the level of the first period to enable further classification of the incoming protocols.

**Comment by SamDecrock** [comment]
Thanks! How does the protocol get the detected now? Does it just assume the first signal is high?

**Comment by Martin-Laclaustra** [comment]
It pays attention only to the timings disregarding whether they are high or low.
For example, these two signals get recognized as the code 1234 (protocol 1, 24 bits) (tested):
![code1234direct](https://cloud.githubusercontent.com/assets/12773403/26222145/300438b4-3c19-11e7-9ef4-3d5cb5d4d3fa.png)
![code1234inverted](https://cloud.githubusercontent.com/assets/12773403/26222151/33055106-3c19-11e7-87f1-05c3ec3e270f.png)
The first signal is the first long timing above a duration threshold that appears twice within a certain timeframe. Then it is assumed high or low (i.e. is ignored) depending which protocol is the one that matches the timings between these long signals.

**Comment by SamDecrock** [comment]
All right.

Thanks for this insightful answer!
