### ISSUE TITLE
Support for CC1101

### ISSUE THREAD

**Issue by martenumberto** [sui77/rc-switch#145]
Is the CC1101 supported by this Library?
I have an Arduino Nano with a CC1101 Chip.
https://www.amazon.com/Solu-Wireless-Transceiver-Antenna-Arduino/dp/B00XDL9838/ref=sr_1_3?ie=UTF8&qid=1494574220&sr=8-3&keywords=cc1101&th=1

**Comment by Locke** [comment]
The CC1101 is not supported by this library. It doesn't provide raw access to the sender/receiver as this library assumes, as it uses it's own package format and has some more complex internal logic to calculate things like a checksum, see http://www.ti.com/lit/ds/symlink/cc1101.pdf#page=37.

It might be worth looking at https://github.com/SpaceTeddy/CC1101. I haven't tried it out though..

**Comment by LSatan** [comment]
Hello,
the theme is a bit older but
it works great with cc1101.
the cc1101 only needs to be configured correctly. got it done the rx demo of rc switch to get running. the nice thing about the cc1101 is that it not only works with 433 mhz. I'm just about to implement the rest. Maybe it helps others.

**Comment by LSatan** [comment]
I managed to make the cc1101 compatible with rcswitch. I have made a kind of driver so that it works. since I have rewrite a lib for someone else I have to wait now for permission to publish it.
Sorry for my Bad english.

**Comment by LSatan** [comment]
The Driver is ready and Works Perfect.

**Comment by LSatan** [comment]
here is the driver:
https://github.com/LSatan/RCSwitch-CC1101-Driver-Lib

**Comment by YindSoft** [comment]
> here is the driver:
> https://github.com/LSatan/RCSwitch-CC1101-Driver-Lib

LSatan, you're a saint!

**Comment by 1technophile** [comment]
Closing the issue as CC1101 is supported by @Lsatan library
