### ISSUE TITLE
Protocol for Kambrook power sockets

### ISSUE THREAD

**Issue by mpember** [sui77/rc-switch#168]
I have a few sockets that appear to be a different protocol to most of the code I've seen.  Currently, the only way I can send the commands is using a C-based program I found here:
http://www.openmediacentre.com.au/tutorials/raspberry-pi/home-automation-with-the-raspberry-pi/

Thanks to the code posted by @Martin-Laclaustra over on another thread, I was able to get a scan of the signal (I think).

The output of the On / Off codes is seen here:
https://cloud.pembo.it/index.php/s/GkhlQdOUyCgVAjb
https://cloud.pembo.it/index.php/s/0aaIartRNRapq8g

Does this make sense to anyone?  Is it possible to create a protocol for this type of code?

**Comment by Martin-Laclaustra** [comment]
1. Paste the numbers instead of pictures.
2. Record "silence". You might be in a RF "polluted" environment. Make sure that you see silence with a low level most of the time. Your reciever could also be failing.
3. Record longer signals (make the buffer bigger in the code). Press your remote a shorter period so you can see silence before and after the signals.

Best luck.

**Comment by mpember** [comment]
> Paste the numbers instead of pictures.

The output from the two codes are:
`97,208,88,194,88,214,86,213,85,188,84,206,52,213,97,184,62,193,53,196,52,203,52,208,85,198,85,207,100,196,99,180,88,192,74,183,94,177,90,209,87,208,53,220,55,214,98,202,86,175,71,196,52,196,99,190,86,187,85,216,85,208,85,174,100,199,86,200,89,189,92,250,47,204,108,187,85,200,92,183,97,177,107,162,70,186,87,177,98,180,86,185,70,186,85,185,109,175,104,174,109,181,74,178,73,184,97,205,87,190,71,193,95,179,72,209,72,178,70,169,60,187,70,200,59,202,70,181,100,180,74,175,103,192,72,184,90,189,90,185,52,185,85,189,85,236,87,198,85,195,71,203,52,196,54,220,86,185,101,294,61,252,72,206,92,217,52,242,87,222,708,30,323,28,592,29,812,28,625,28,623,35,684,275,30,346,29,297,28,331,35,328,36,642,31,346,28,270,36,302,35,273,41,291,29,268,35,309,35,303,35,386,294,35,336,277,35,356,35,518,29,275,38,317,28,281,35,280,41,366,28,269,36,311,35,730,29,276,28,324,30,322,35,297,34,634,35,304,28,377,341,262,29,380,28,320,35,305,35,324,35,329,35,481,30,638,36,292,35,324,36,340,29,489,29,299,38,377,43,254,43,330,42,257,51,257,52,219,158,197,97,172,95,172,130,52,201,56,182,106,49,168,35638,246,88,261,58,245,53,234,87,262,53,222,60,264,43,214,86,232,43,260,54,190,52,207,70,229,53,194,52,219,42,240,94,192,71,204,56,212,53,223,53,220,74,233,86,217,70,215,52,231,51,207,53,205,52,271,52,228,71,209,51,198,71,235,51,237,71,215,53,204,51,198,52,212,71,201,54,234,69,200,60,229,55,227,43,226,84,226,53,221,87,251,41,218,52,216,60,223,43,218,53,245,42,223,53,230,61,208,43,230,53,217,70,275,42,213,60,211,86,221,87,208,52,243,52,214,70,226,76,201,89,197,72,221,53,213,61,240,53,213,53,236,44,224,52,225,70,209,51,192,52,214,52,207,85,199,52,252,72,241,53,214,74,198,86,226,85,210,99,268,54,226,88,214,60,191,58,206,85,206,87,230,53,208,88,204,85,201,55,201,71,193,57,213,53,249,85,208,42,219,52,210,52,208,53,214,85,214,53,176,85,207,52,214,53,211,85,208,85,198,53,230,70,218,52,246,75,216,54,201,70,222,70,220,86,203,90,250,53,233,44,238,42,207,52,211,52,201,51,254,52,236,51,218,86,246,56,210,52,223,43,222,52,211,42,210,72,213,92,233,51,209,72,216,53,211,85,188,52,214,52,219,52,261,54,230,52,233,53,219,53,217,54,220,53,223,55,210,51,204,86,235,86,205,54,201,70,190,89,233,61,211,54,189,70,205,91,186,52,222,71,226,91,212,53,196,86,214,85,202,52,205,87,197,85,187,98,199,85,251,43,249,72,215,86,213,85,220,71,209,89,232,71,210,49,300,42,225,52,236,52,234,51,209,51,253,42,11392,29,637,1659,29,497,343,35,691,30,823,29,581,28,578,1196,28,1064,28,963,29,1349,3519,576,1045,317,52,300,88,251,62,222,104,217,53,220,71,194,54,213,73,227,73,201,86,227,43,187,85,200,85,193,51,237,88,200,71,227,44,212,86,179,52,177,71,199,88,181,71,198,96,179,87,189,54,186,86,211,89,229,86,192,90,189,90,218,70,250,43,209,85,184,52,199,85,203,91,193,94,194,89,214,74,210,90,188,98,180,91,215,73,208,109,219,52,183,60,196,71,215,88,188,52,193,51,201,87,213,85,193,97,224,87,219,71,225,71,199,52,222,52,207,54,239,53,247,100,198,54,234,52,213,52,211,85,201,86,200,52,223,52,191,52,201,97,205,70,181,84,202,72,222,70,199,54,194,53,186,52,207,71,217,97,201,88,203,86,193,52,194,85,229,89,196,53,211,99,205,91,198,89,296,54,207,52,194,93,184,52,188,86,193,85,181,86,185,91,189,73,189,54,189,96,190,58,202,89,204,88,188,90,185,73,205,52,200,70,178,71,189,86,218,72,217,86,208,86,216,95,195,95,174,52,225,84,229,55,209,86,243,53,213,94,192,71,204,52,193,85,201,90,202,139,257,85,218,84,211,89,183,53,207,53,230,72,208,52,215,43,181,73,183,85,214,52,188,74,197,85,229,45,210,87,231,52,186,85,190,86,201,52,222,58,231,61,191,72,248,76,183,108,214,85,212,71,201,73,204,70,198,87`

AND

`180,79,186,75,187,79,177,71,179,68,183,83,176,70,194,74,196,78,174,91,164,75,190,80,178,84,172,78,223,87,179,71,201,72,182,69,184,74,187,83,186,73,188,74,190,83,185,89,197,87,198,83,193,83,185,73,197,80,171,71,188,57,206,63,201,69,209,78,214,74,171,90,190,80,181,76,193,70,191,90,162,89,162,81,163,67,171,86,195,71,176,85,170,85,166,89,168,79,193,76,192,79,184,63,188,75,171,77,202,75,179,73,181,90,169,79,168,72,160,55,168,80,177,73,175,87,206,74,180,90,181,71,165,88,176,89,183,91,154,90,171,91,165,96,211,91,185,32326,250,60,238,68,229,77,225,70,216,62,230,58,256,48,254,77,223,47,247,69,234,58,217,63,260,53,254,59,229,71,230,68,213,64,216,56,237,71,218,77,214,71,204,70,206,67,222,55,238,66,229,82,217,74,273,61,228,63,214,71,208,75,230,71,233,64,229,71,223,78,217,63,223,66,201,72,204,61,225,64,238,43,207,63,210,61,235,57,211,70,195,65,217,68,194,60,208,62,190,71,206,62,192,72,191,66,211,65,234,72,253,51,217,71,229,53,213,72,209,49,228,69,204,104,224,73,229,56,225,57,220,71,206,65,207,70,206,70,187,59,226,63,211,68,192,67,214,68,223,62,245,70,284,58,249,70,225,60,232,62,217,73,205,72,209,62,232,74,224,71,193,72,202,69,210,80,201,64,206,64,198,66,219,73,207,77,194,65,199,71,200,65,223,73,204,83,188,77,202,69,198,80,199,62,212,76,192,83,206,84,204,87,202,72,207,67,188,60,222,66,192,69,258,247,74,189,70,208,74,218,78,209,72,217,73,204,68,205,70,214,64,200,68,206,63,207,77,223,76,221,62,193,67,192,81,195,65,229,67,225,61,213,69,203,93,189,54,213,65,219,65,224,79,205,73,212,65,216,76,215,55,242,66,216,73,204,83,213,71,203,73,212,64,225,56,232,77,200,59,208,72,206,79,182,67,185,71,200,72,219,78,207,56,216,83,199,74,194,67,219,66,219,83,206,77,199,67,183,83,180,73,209,73,193,66,203,65,201,61,220,79,217,77,203,96,174,74,186,71,199,73,202,82,213,77,188,73,195,70,198,72,170,59,190,74,190,102,208,82,204,75,199,83,180,75,209,70,211,85,200,71,192,72,213,67,195,72,193,64,203,66,212,76,195,65,206,74,225,72,187,67,218,70,208,74,239,73,198,66,211,69,185,58,216,65,202,64,220,84,212,68,198,73,205,80,213,62,215,65,204,75,195,67,198,77,187,66,207,67,217,59,209,77,228,77,200,72,197,80,174,78,188,66,201,82,222,81,188,75,230,77,199,81,166,72,180,75,205,76,190,70,197,84,172,74,181,72,186,75,187,82,163,68,179,90,174,64,189,79,216,72,196,71,181,80,185,77,182,62,182,80,178,83,191,63,195,66,200,82,191,65,208,80,202,77,213,78,190,62,204,75,192,81,188,83,164,57,187,62,185,81,181,70,173,77,172,64,170,76,210,63,217,78,184,54,196,83,179,78,175,74,196,66,207,77,175,70,186,77,178,78,181,58,194,66,199,58,196,67,179,63,184,77,188,68,168,77,205,65,184,68,177,70,185,76,179,83,180,74,176,71,863,73,308,65,198,72,194,83,176,77,174,89,195,62,211,80,184,76,179,61,188,92,182,66,192,77,179,78,186,86,185,72,179,75,176,79,171,81,175,88,190,69,202,82,182,83,199,109,177,77,195,83,193,97,175,83,186,75,181,77,204,69,171,80,189,70,190,78,162,70,203,64,185,72,184,68,194,63,203,84,177,77,181,84,196,84,177,77,187,72,183,63,187,89,194,84,165,73,182,71,200,78,201,67,182,71,197,73,236,76,196,70,200,76,195,84,207,72,201,76,214,72,198,91,188,70,186,72,176,75,182,68,221,62,189,72,183,71,182,74,196,78,202,86,216,63,203,82,187,83,168,86,194,85,181,71,184,71,162,68,195,84,201,72,189,86,208,73,205,76,164,79,184,65,172,83,196,78,181,80,182,83,170,87,157,66,179,84,168,74,172,67,186,73,174,90,169,71,168,68,165,74,167,80,187,112,60,170,81,173,80,166,79,201,76,166,74,170,72,193,76,191,113,223,60,185,81,190,70,186,75,174,72,196,82,165,58,169,77,175,85,172,74,179,84,176,71,190,69,203,74,207,84,174,77,190,65,198,80,205,65`

> Record "silence". You might be in a RF "polluted" environment.

That is likely.  The smart meters rolled out in our area are often paired with 433mhz-based displays to let the residents monitor their power usage.

Here is 'silence':
`222,60,190,75,192,68,201,64,211,72,212,80,206,78,197,69,210,52,245,74,182,74,188,54,224,84,213,91,193,69,189,67,180,69,178,79,203,79,179,92,194,89,182,64,212,80,249,63,191,79,192,81,169,76,193,78,190,88,197,28361,288,59,334,59,262,50,298,54,260,48,511,53,280,60,220,63,215,62,259,60,250,67,266,49,271,56,225,63,229,58,204,51,299,49,370,50,287,64,272,66,263,56,262,59,299,57,262,74,255,64,238,73,217,55,234,74,249,58,239,67,287,47,255,71,240,56,251,65,264,61,241,71,258,62,225,71,228,61,250,60,245,66,235,66,236,61,222,59,240,55,253,61,227,61,228,76,249,62,406,56,253,75,232,53,237,64,245,80,213,67,214,45,257,73,232,58,271,61,249,74,222,66,219,60,254,61,238,53,244,61,241,63,246,69,239,57,230,72,263,56,237,47,270,64,248,69,244,60,232,66,255,64,219,67,236,59,258,69,237,65,218,71,295,47,274,53,263,73,227,61,232,75,243,59,237,73,234,69,220,70,223,71,219,63,240,63,256,66,240,70,227,61,220,63,246,66,241,71,217,69,213,73,227,72,226,67,217,68,212,64,214,72,215,66,220,68,238,48,246,74,218,66,201,68,213,60,227,76,215,68,240,61,225,76,205,60,213,74,220,62,216,75,205,62,241,51,225,61,239,75,217,66,228,68,222,63,237,68,239,63,235,76,239,50,239,71,250,61,240,62,247,73,241,64,250,58,249,54,272,67,247,68,213,64,223,60,244,72,203,64,240,70,210,63,213,72,229,73,258,56,237,82,225,17,199,65,183,66,212,65,240,66,213,64,213,67,214,75,210,61,224,80,224,77,202,62,287,66,227,66,218,83,207,67,209,70,191,72,205,74,207,65,191,63,187,67,198,68,239,69,203,78,205,76,211,58,207,65,199,61,216,67,222,71,211,74,221,72,204,64,186,83,203,71,188,67,213,76,181,73,195,57,194,82,230,59,198,79,189,76,188,69,201,73,198,74,189,70,227,60,215,66,219,69,209,68,249,66,244,67,225,69,202,76,202,79,237,59,244,73,221,83,204,72,212,70,216,72,218,78,232,76,216,68,203,66,221,73,237,62,270,61,222,69,223,86,205,59,199,75,216,63,194,73,225,74,199,68,205,85,221,71,184,67,194,78,180,54,231,82,189,72,184,68,196,65,203,74,202,76,192,85,193,74,209,82,194,68,206,66,183,82,203,80,182,76,210,74,251,78,194,77,193,81,201,80,187,63,225,58,201,115,202,68,180,60,177,63,178,80,195,77,190,96,181,66,187,64,206,73,185,85,171,66,211,62,202,77,198,70,216,74,187,70,190,67,202,76,198,70,205,64,227,67,211,65,208,69,225,75,230,81,213,71,200,66,193,59,210,70,209,103,195,69,214,74,188,84,185,65,197,71,204,76,214,70,221,65,231,67,199,85,183,79,187,69,195,66,199,80,192,75,162,71,188,76,187,69,195,73,188,66,210,80,192,71,231,83,190,71,178,63,182,90,192,74,188,79,188,66,174,81,184,93,179,73,181,83,223,74,196,77,198,87,189,69,183,78,182,72,179,96,200,73,204,75,186,75,201,87,310,77,172,80,183,65,202,84,195,90,174,87,173,84,218,70,203,80,178,71,193,81,200,68,184,88,183,67,181,71,202,74,226,67,225,73,212,77,206,70,212,74,204,67,196,65,201,74,185,79,188,63,201,81,237,75,186,74,188,66,188,77,170,69,189,75,171,70,183,70,196,74,186,49,230,68,188,77,172,66,200,65,205,82,210,75,184,66,190,89,173,84,164,69,197,75,203,89,182,77,199,69,185,82,180,74,167,75,164,74,175,69,181,70,183,72,181,81,170,61,178,76,192,79,250,64,187,79,197,67,187,94,177,66,186,54,233,86,174,85,182,80,202,70,175,74,184,70,235,51,191,72,192,80,184,90,181,76,189,87,178,75,173,71,189,103,172,77,183,96,175,73,188,72,186,71,183,73,195,70,197,70,194,73,196,76,206,73,214,80,177,69,220,67,273,69,200,72,212,72,217,98,177,78,197,86,171,80,180,78,189,67,186,85,164,70,162,64,196,74,231,76,176,83,215,90,196,66,200,73,198,78,180,97,199,76,200,94,161,82,199,90,179,89,163,99,180,73,182,57,180,92,64,216,87,175,85,163,94,152,92,159,82,166,92,172,109,51,188,37051,233,61,223,66,220,56,245,51,309,68`

> Record longer signals (make the buffer bigger in the code). Press your remote a shorter period so you can see silence before and after the signals.

I am currently using the transmitter in the Pi to send the signal.  The program that sends the signal repeats the transmission exactly 5 times.  I can recompile the program to send a smaller number of repeats, or extend the wait between repetitions.  I had already extended the buffer from 500 to 1000.

Is there any reason I shouldn't temporarily jumper the GPIO pin being used to send the code to the GPIO pin being used to receive the code?

Does the reference in [the above link](http://www.openmediacentre.com.au/tutorials/raspberry-pi/home-automation-with-the-raspberry-pi/) offer any guides on how best to replicate the protocol?

>A digital zero: is an on pulse of 280ms followed with an off pulse for 300ms
A digital one: is an on pulse of 650ms followed with an off pulse for 300ms
The gap in-between the 5 messages is 9850ms

I got confused when the protocol definitions started talking about 'sync_high' and 'sync_low' parameters.

**Comment by Martin-Laclaustra** [comment]
The protocol seems simple:
{ 290, { 1, 34 }, { 1, 1 }, { 2, 1 }, false }
The problem is that rcswitch currently has a limit of 32 bits if you do not change the length of the variables in the library (and in 433utils, if you use them) that hold the code to send.
According to your link, every signal is pre-pended:
01010101000000000011011001101000
(32bits)
then you have to insert the codes of your sockets (what is the length?)
and the append:
11111111
(8bits)
Only the fixed bit amount for 40bits.
Is there a particular reason why you want to use rcswitch?

**Comment by mpember** [comment]
> Only the fixed bits amount for 40bits.
The fixed part is that all codes start with "11111111" and end with "01010101".  The full code is 48 bits long. The rest defines the 'group', 'socket' and 'state' being sent.

e.g.
The full signal transmitted for a ON command would look like this:
01010101000000000011011001101000001000**01**11111111 **(93459401155071)**
01010101000000000011011001101000001000**10**11111111 **(93459401155327)**

> Is there a particular reason why you want to use rcswitch?
I would like to reduce the need to have my code use two different ways of transmitting the RF codes.  Since there is a python-based system that appears to accept the same 'protocols' as rcswitch, I was hoping to remove the need for an external binary.

The python port of rc-switch I am using can be found here:
https://github.com/milaq/rpi-rf

It works fine with the sockets I own that support 'protocol 1'.

**Comment by Martin-Laclaustra** [comment]
Suggested changes to RCSwitch to allow for very long codes (>32 bits)

**RCSwitch.h**
line 80
`void send(unsigned long code, unsigned int length);`

`unsigned long` to `unsigned long long`

**RCSwitch.cpp**
line 486
`void RCSwitch::send(unsigned long code, unsigned int length) {`

`unsigned long` to `unsigned long long`

line 500
`if (code & (1L << i))`

`1L` to `1LL`


I did not test these changes. Please report back if you take on this path.

**Comment by mpember** [comment]
@Martin-Laclaustra 

I had an attempt.  The scanner never displayed any output.other than a screen full of 0s.

Since the reason I started down this path was to try and replace an executable with a python equivalent, I have decided to simply replace the few Kambrook sockets that use the unsupported protocol.

I appreciate all the assistance.  In the end, it will be easier to give the Kambrook sockets to a mate who already has a number of them.  Since he is not using a python-based setup, the advantage of an all-Python codebase isn't applicable.

**Comment by Martin-Laclaustra** [comment]
Please reopen the issue to be able to dicuss here.

Updated protocol according to your recording that you posted in the other thread.

{ 360, { 1, 1000 }, { 1, 1 }, { 2, 1 }, false }

Beware of 1000, try smaller values (your recorded signal showed variable gaps > 3000 * 360). You will not be able to DETECT this protocol but it should be easy to send it.
Modify the size of the variables as explained above.
Use this updated protocol.
If this does not trigger your plug, record the signal that you generate with rcswitch and compare it with the signal that actually does trigger the plug.

The 3 signals you recorded were not exactly equal. The first two signals were 47 bits and the last one 48 bits (your OFF signal: 010101010000000000110110011010000010001011111111; the first signals missed the first 0).

**Comment by mpember** [comment]
I appreciate the help.  I have already given away my Kambrook sockets. As such, my only chance to test your code will be when I assist my mate with setting them up on his Pi.  I'll see how I go.  It will depend on when we are both free.  I'll keep you posted.

Thanks.
