### ISSUE TITLE
Question for receiving signals

### ISSUE THREAD

**Issue by chmasi** [sui77/rc-switch#188]
Hi Guys
Is it possible to receive and display signals which are in an unknown format?

lets assume I send: temp=10.0, humidity=1005, rain=300

can I receive it and display it without having a protocol behind?

Thanks 
Martin

**Comment by 1technophile** [comment]
Hi,

Sorry but I don't understand well the question, do you mean capturing raw signals?
If this is what you are expecting you can take a look to simpleRCScanner.
Nevertheless RC-switch currently doesn't support weather stations.

Regards
