### ISSUE TITLE
Signal Mess?

### ISSUE THREAD

**Issue by trkmml** [sui77/rc-switch#191]
Hello there,
I control 2 arduino transmitters and 2 rf relays in the same room. I am sending a relay "1020101" with the code I use with the library and another relay "1020102" with the other arduino. these two codes are sometimes interfering and activating the wrong relay. is that the reason codes are close to each other?
my code example: "mySwitch.send (" 1020101 ", 24);"
Should I use a different data type?

**Comment by 1technophile** [comment]
Hello,

You should try more different codes like 1020101 & 1020222
