### ISSUE TITLE
generic SetProtocol method

### ISSUE THREAD

**Issue by clyss** [sui77/rc-switch#200]
Hello,
I need to set the protocol to :
{ 749, { 36, 1 }, { 1, 2 }, { 2, 1 }, true }

I tried to add a setProtocol method without success

setProtocol (Protocol P)
to call setProtocol( { 749, { 36, 1 }, { 1, 2 }, { 2, 1 }, true });

If easier, setProtocol (Protocol P) could change the definition of Protocol 1 (or another..)

Could someone help me to write it , that we add to  the repo?
Thanks

**Comment by 1technophile** [comment]
Hello,

Currently you need to add your protocol to[ rcswitch.cpp](https://github.com/sui77/rc-switch/blob/6d4fff8d1c819cc59c5bbc8aea23324df89dd4cd/RCSwitch.cpp#L82) and reupload your code.

Regards
