### ISSUE TITLE
Are these remotes supported? 

### ISSUE THREAD

**Issue by Kepete** [sui77/rc-switch#202]
I can't find what protocols these two remotes are using. I searched the web but nothing. Maybe someone knows. 

- Chamberlain Liftmaster 4330E 4332E 4333E 4335E  [https://www.ebay.com/itm/Liftmaster-Chamberlain-4330E-4332E-4333E-4335E-compatible-remote-control-433-92/171889320477?hash=item280566e21d:g:Ga0AAOSwT6pVzLfy](url)
- Chamberlain Motorlift 84333EML  [https://www.ebay.com/itm/Chamberlain-Liftmaster-Motorlift-84333EML-94333E-Rolling-code-433-92-Mhz/322973685539?hash=item4b32bb5723:g:7FkAAOSw-KFXeYBi](url)

Are these supported? 
I would like to use my Raspberry Pi 3 to send RF signal to open my garage door/gate.

**Comment by 1technophile** [comment]
As they seems to use a rolling code I can confirm that RCSwitch will not support your garage door opener.

> I would like to use my Raspberry Pi 3 to send RF signal to open my garage door/gate.
Maybe another solution is to put a wifi relay (like a sonoff) on your garage door and control it from your pi
