### ISSUE TITLE
RF transmission between Arduino Uno and nodeMCU ESP32

### ISSUE THREAD

**Issue by tzekianooi** [sui77/rc-switch#215]
Hi. Is it possible to have RF transmission between the 2 boards? I am using the 315MHZ FS1000A transmitter on Uno and RF-5V receiver on ESP32. Both compile and upload successfully, but on the serial monitor of the ESP 32 COM port, nothing is shown on the monitor. Both baud rate are set at 9600. Has anyone tried this before? Kindly give me some advice on this issue please. Thank you.

**Comment by 1technophile** [comment]
Hi,
Yes it should work, I'm sending and receiving between Arduino Mega, ESP32 and ESP8266
