### ISSUE TITLE
Kernel panic saving rf value to eeprom

### ISSUE THREAD

**Issue by 7i77an** [sui77/rc-switch#217]
I have kernel panic when process rf vale and save this into eeprom. 

Version used: rc-switch 2.6.2
Hardware: WEMOS LOLIN32
Arduino IDE ver: 1.8.5

ESP Exception decoder:

0x400ec8ec: pthread_getspecific at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/pthread/./pthread_local_storage.c line 173
0x400ec8ec: pthread_getspecific at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/pthread/./pthread_local_storage.c line 173
0x400ec8ec: pthread_getspecific at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/pthread/./pthread_local_storage.c line 173
0x40080ebf: RCSwitch::handleInterrupt() at C:\Users\titan\Documents\Arduino\libraries\rc-switch/RCSwitch.cpp line 479
0x40080f6d: __onPinInterrupt at C:\Users\titan\Documents\Arduino\hardware\espressif\esp32\cores\esp32/esp32-hal-gpio.c line 211
0x40081781: _xt_lowint1 at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/./xtensa_vectors.S line 1105

    Device* devices = objRF->GetDevices();            
    HubInfo ihub; 
    memset(&ihub, 0, sizeof(ihub));
    ihub = objEEPROM->Get();   
    memcpy(ihub.devices, devices, sizeof(ihub.devices));
    objRF->DisableReceive(); --->>
    objEEPROM->Put(ihub);
    objRF->EnableReceive(); -->>

I need put this lines (-->>) to disable interrupt rf, save eeprom data and enable again rf.
I suppose the problem is associated with issue #46, but in practice it is not working.

**Comment by micha6554** [comment]
Thanks!!!

**Comment by 1technophile** [comment]
Thanks for the info
