### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by X-Dron** [sui77/rc-switch#227]
PLS add ESP32 support to the interrupt handler.
#ifdef ESP8266
    // interrupt handler and related code must be in RAM on ESP8266,
    // according to issue #46.
    #define RECEIVE_ATTR ICACHE_RAM_ATTR
#elif ESP32
	#define RECEIVE_ATTR IRAM_ATTR
#else
    #define RECEIVE_ATTR
#endif
See
https://github.com/espressif/arduino-esp32/issues/855
Other cases of using #ifdef ESP8266  I did not test.

**Comment by ttww** [comment]
Vote 👍

**Comment by pemca** [comment]
Hi,

Working fine 👍 

I changed locally in RCSwitch.cpp To

#ifdef ESP8266
    // interrupt handler and related code must be in RAM on ESP8266,
    // according to issue #46.
    #define RECEIVE_ATTR ICACHE_RAM_ATTR
#elif ESP32
    #define RECEIVE_ATTR IRAM_ATTR
#else
    #define RECEIVE_ATTR
#endif

FROM
/*
#if defined(ESP8266) || defined(ESP32)
    // interrupt handler and related code must be in RAM on ESP8266,
    // according to issue #46.
    #define RECEIVE_ATTR ICACHE_RAM_ATTR
#else
    #define RECEIVE_ATTR
#endif
*/

And in my ESP32 Code 
#
#include <WiFi.h>
#include <PubSubClient.h>
#include <RCSwitch.h>

#define ESP32

And it works fine
/Peter

**Comment by mattjarvis** [comment]
This sorts it! Cheers!

**Comment by 1technophile** [comment]
The current code in master branch supports already ESP32
