### ISSUE TITLE
Implement RF HT6P20B

### ISSUE THREAD

**Issue by ricardojlrufino** [sui77/rc-switch#23]
I tried but did not succeed.

Datasheet 
http://www.holtek.com.cn/PDF/consumer/HT6P20x2v110.pdf

Ref:
http://arduinobasics.blogspot.com.au/2014/06/433-mhz-rf-module-with-arduino-tutorial.html

**Comment by ricardojlrufino** [comment]
Done...
https://github.com/sui77/rc-switch/pull/24

**Comment by fingolfin** [comment]
Without any test hardware, it is impossible for us to implement this, I am afraid, so it's up to others to contribute the code. Unfortunately,  PR #24 which you made for this never was updated to address questions and comments.

**Comment by bau-sec** [comment]
PR #49 should add support for this.
