### ISSUE TITLE
40 bit long code

### ISSUE THREAD

**Issue by gmiller01** [sui77/rc-switch#232]
Hi guys,

I have a rolo shutter remote. I have decoded it, but this remote has 40 bits long code.
The rc-switch is cutting at 32 bits, because a long variable store the code.
Is this any workaround for 40 bits remote controller?

**Comment by Martin-Laclaustra** [comment]
https://github.com/sui77/rc-switch/wiki/Add_New_Remote_Part_2

**Comment by gmiller01** [comment]
Thank you :-)
