### ISSUE TITLE
constantly getting codes without pressing any button

### ISSUE THREAD

**Issue by earth08** [sui77/rc-switch#249]
Dear,
Please guide
i am using srx882 and nodemcu,
i am trying with receivedemo_advanced example. where i am getting constant codes without pressing any button of my remote.
Please guide
following are codes which i am getting

⸮)Decimal: 47 (6Bit) Binary: 101111 Tri-State: not applicable PulseLength: 5 microseconds Protocol: 0
Raw data: 6140,31,5,5,5,6,5,5,5,5,5,5,5,

Decimal: 127 (7Bit) Binary: 1111111 Tri-State: 111 PulseLength: 5 microseconds Protocol: 0
Raw data: 5204,19,5,5,5,5,5,5,5,5,5,5,5,5,5,

Decimal: 63 (6Bit) Binary: 111111 Tri-State: 111 PulseLength: 5 microseconds Protocol: 0
Raw data: 5907,24,5,5,5,5,5,5,5,5,5,5,5,

Decimal: 31 (5Bit) Binary: 11111 Tri-State: 11 PulseLength: 5 microseconds Protocol: 0
Raw data: 5860,28,5,5,5,5,5,5,5,5,5,

Decimal: 63 (6Bit) Binary: 111111 Tri-State: 111 PulseLength: 5 microseconds Protocol: 0
Raw data: 5975,59,7,5,5,5,5,5,5,5,5,5,5,

Please guide me to get my problem solved
I am using Geekcreit 12v 4ch relay switch rf 433

**Comment by Schneemann2** [comment]
Do you have neighbors?

**Comment by earth08** [comment]
Sorry to let you know,
I solved the problem.
As I have not connected ground to the board.
After connecting everything is working.
Thanks

**Comment by earth08** [comment]
Sorry to let you know,
I solved the problem.
As I have not connected ground to the board.
After connecting everything is working.
Thanks
