### ISSUE TITLE
Problems adding a new protocol

### ISSUE THREAD

**Issue by aussieW** [sui77/rc-switch#252]
Hi 

I am trying to add a new protocol for the Heller iRemote (also sold under the OWL brand).
![image](https://user-images.githubusercontent.com/1840035/44232949-e49edf80-a1e5-11e8-8489-63d042e932d4.png)

 I have captured and analyzed the signal and added the following line to RCSwitch.cpp
{ 447, { 0, 8 }, {1, 2}, {2, 1}, false },               // iHeller

The timings generated by rc-switch seem spot on when I compare to the original remote. The screenshot below show the two signals in audacity.

![selection_001_1](https://user-images.githubusercontent.com/1840035/44233263-b1a91b80-a1e6-11e8-9279-a35432c740da.png)

The screen shot shows the following signal being sent
mySwitch.send("1100000100111000000010110000100100");

The first two bits should be ones but as highlighted in the screenshot, they are coming out as zeros.  

Any suggestions on how to address this issue.

Thanks
aussieW

**Comment by Martin-Laclaustra** [comment]
You are sending 34 bits.
The way the library sends "text" binary is by converting it to a 32 bits int (variable called "code"), by bitshifting:
https://github.com/sui77/rc-switch/blob/a9da9c36820b02fc5613dfe2437e1187bcf5b402/RCSwitch.cpp#L474-L476
Your first 2 bits just "fall off" the integer and are lost. Thus, they are send as 0s.
You should change the library lines to cope with 64 bits codes.
See:
https://github.com/sui77/rc-switch/wiki/Add_New_Remote_Part_2

**Comment by aussieW** [comment]
Thanks. For the info. I found that the instructions for handling 64bit codes on https://github.com/sui77/rc-switch/wiki/Add_New_Remote_Part_2 did not work for me. I ended up appyling the changes in detailed here https://github.com/sui77/rc-switch/pull/221 and now transmit is working.

**Comment by aussieW** [comment]
Just for completeness of the record, I got this remote to work on the unmodified 32 bit version rc-switch by using the following protocol, which combines the last bit and the sync bit together.
{ 447, { 1, 10 }, { 1, 2 }, { 2, 1}, false }

I also got it to work under a modified 64 bit version of rc-switch (after applying the patches from issue https://github.com/sui77/rc-switch/pull/221) using the following protocol
{ 447, { 0, 8 }, { 1, 2 }, { 2, 1}, false }
