### ISSUE TITLE
Interfacing temperature sensor

### ISSUE THREAD

**Issue by roccomuso** [sui77/rc-switch#26]
What happen if I try to detect a temperature sensor?
What rc-switch library provides to me? weird integer codes?

**Comment by Matzz** [comment]
Some time ago I tried to detect temperature data using rc-switch. I didn't get anything. RC switch treated this input as noise.

**Comment by gorec2005** [comment]
temperature sensors have a very different and more complicated protocols depend from vendor/maker...

**Comment by HakimSMH** [comment]
I have some "Door Opening" sensors. RC-Switch doesn't get anything as well, i thought the problem was with the 32bits limitation of RC-Switch, as my sensor is 36bits. Any solution ?

**Comment by roccomuso** [comment]
Have your door sensor a supported chipset? I had no trouble with a PIR sensor.

**Comment by SunboX** [comment]
I have a `COCO KlikAanKlikUit AMST-606` door/window sensor. RCSwitch doesn't recognize anything (sadly). RFControl recognizes some data if I open/close the switch, but I can't use taht data out of RFControl.

**Comment by SunboX** [comment]
Here's some info about the protocol of my sensor: https://github.com/pilight/pilight/blob/master/libs/pilight/protocols/433.92/arctech_contact.c

**Comment by SunboX** [comment]
Found a library that works :smile: -> https://bitbucket.org/fuzzillogic/433mhzforarduino/wiki/Home (NewRemoteSwitch)
