### ISSUE TITLE
Kaku KlikAanKlikUit Protocol

### ISSUE THREAD

**Issue by bitboy85** [sui77/rc-switch#265]
Hi everyone.

Is it possible to add Kaku Protocol for send and recieve? https://manual.pilight.org/protocols/433.92/switch/kaku.html
As you can see in the doc one bit has 4 pulses and it also uses a header and a footer.
[i know there is another library for this but i don't want to use two different at the same time.]

**Comment by 1technophile** [comment]
Hi,

For the moment please take a look to:
https://github.com/1technophile/NewRemoteSwitch
