### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by HakimSMH** [sui77/rc-switch#27]
The code is rather well documented, but i still have some troubles understanding the signification of the changeCount, repeatCount and the Timings array. Would be glad if you could comment them.

In addition, but it perhaps due to my weak experience, i didn't get the Protocols signification in terme of each member of the structure and How to use them. As I have some 433Mhz sensors that RCSwitch doesn't get i thought i could add in some new protocols.

Thanks

**Comment by sui77** [comment]
repeatCount: A remote sends its code repeatedly as long as you press the button. A signal is only classified as received when it is received twice in a row - if (repeatCount == 2) { ... }

changeCount: RCSwitch::handleInterrupt() is called whenever the signal changes from high to low and vice versa. Have a look at https://github.com/sui77/rc-switch/wiki/KnowHow_LineCoding 
When the long low sync signal is detected ( if duration > RCSwitch::nSeparationLimit ) it will assume a new signal is starting ant thus set changeCount=0 and save all following times between high/low states in timings[changeCount++]. 
The timings array is then evaluated in RCSwitch::receiveProtocol.

**Comment by HakimSMH** [comment]
Thank you ! It makes things clearer :)
