### ISSUE TITLE
ESP8266 build-in LED

### ISSUE THREAD

**Issue by SampusCZE** [sui77/rc-switch#271]
Hi,
is there any way to disable build-in LED? 

When i upload transmiting sketch with rc-switch lib. built-in led is still turned on and flashing while transmitting. Is a bit annoying.

Tested with Wemos D1 mini, NodeMcu so far.

**Comment by RO-ny9** [comment]
Hi, did it work with Wemos D1 mini? 
I am trying, but without any success... please can you send me code that you used with wemos D1? Thanks!

**Comment by 1technophile** [comment]
> When i upload transmiting sketch with rc-switch lib. built-in led is still turned on and flashing while transmitting. Is a bit annoying.
> 
> Tested with Wemos D1 mini, NodeMcu so far.

Hi,

You could use a different pin for transmitting (not used by the BUILD_IN led)
