### ISSUE TITLE
ESP32 - receiver is not working on some GPIOs

### ISSUE THREAD

**Issue by DavidAntonin** [sui77/rc-switch#278]
Hello, I have a problem with receiver on GPIOs 25,26,32,33,34,35. On GPIO4 everything is working without problem. Thanks
David

**Comment by aaronmcniven** [comment]
Any way to fix this? Was wanting to use GPIO26. Hardware limitation? :(

**Comment by aaronmcniven** [comment]
Update: Managed to get GPIO26 working for me.

I added:

pinMode(RF_RX_PIN, INPUT_PULLUP);
RCS.enableReceive(RF_RX_PIN);

**Comment by 1technophile** [comment]
Depending on the pins ability to handle interrupts you can or canno't use them as the receiver pin. This is normal, take a look to the datasheet of the board to have further information.
If you have other question don't hesitate to comment.
