### ISSUE TITLE
IRhvac

### ISSUE THREAD

**Issue by pcpaulo** [sui77/rc-switch#279]
I have installed the latest version of Tasmota 6.4.1.19 and i would like to use the irhvac command, every time that i am using i receive a message 

21:20:16 CMD: IRHVAC
21:20:16 MQT: stat/infrared/RESULT = {"Command":"Unknown"}

Any direction to use it?

**Comment by muslimtabahwaskito** [comment]
can you solved it? i have same problem like you..

**Comment by 1technophile** [comment]
Sorry but maybe I missed something, to my knowledge Rc switch is dedicated to Radiofrequencies. You should better look for irremote library.

**Comment by iq85k** [comment]
you have to use the Tasmota-IR.bin

**Comment by muslimtabahwaskito** [comment]
oh finally i can solve my problem.. thanks

**Comment by iq85k** [comment]
anytime :)
