### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by lunarbase** [sui77/rc-switch#28]
I read on instructables.com that your library can stiff a code from a remote control and play that later? Is it true? can it sniff rolling code remotes? Thanks.

**Comment by sui77** [comment]
No, it's limited to a bunch of fixed code protocols that are used on low cost devices.

The thing with rolling codes is that - even when you can sniff it - you also need to know how transmitter + receiver are synchronized.

**Comment by lunarbase** [comment]
OK. Thanks for the answer
