### ISSUE TITLE
rc-switch based IoT 433mhz system 

### ISSUE THREAD

**Issue by roccomuso** [sui77/rc-switch#29]
Hi guys,

I just wanna show you my new repo that use rc-switch. There's something in common with other iot famous project but also really different implementations and features..

https://github.com/roccomuso/iot-433mhz

Any feedback would be appreciated. Thanks!

**Comment by fingolfin** [comment]
Good luck with your project!

However, this is an issue tracker, not a system for collecting links, so I am closing this now :)
