### ISSUE TITLE
Partial Rust port of rc-switch

### ISSUE THREAD

**Issue by flxo** [sui77/rc-switch#294]
Hi,

just want to let you guys know that I did a partial port of `rc-switch` in Rust.

https://github.com/flxo/funksteckdose (yes naming is hard here...)

The port doesn't support reception and only works in conjunction with `WringPI` atm.
I *didn't* invent something new and just borrowed your work. Thanks!
Feel free to close this issue immediately .

Thanks
@flxo

**Comment by 1technophile** [comment]
Thanks for the info
