### ISSUE TITLE
Can this library be generalized?

### ISSUE THREAD

**Issue by regexstrings** [sui77/rc-switch#298]
I apologize for the my basic question; I'm new to this.

I've found the rc-switch library to be highly effective when working with 433mhz remotes.  But now I want to explore other 433mhz products like a digoo weather station (bg-th8380).  Is it possible to use the rc-switch library to watch traffic between a 433mhx weather sensor and a 433mhz weather station?   I guess I'm looking for a library that can watch for any 433mhz traffic and then let me parse and act on it how ever I want.  As a first step I want to see all 433mhz traffic ....

Regardless, this library rocks.  Just wondering if I can build something more generalized on it.

**Comment by 1technophile** [comment]
You can take a look to pilight, it already decode 433mhz weather stations and you have a port for ESP esppilight
