### ISSUE TITLE
Access to the repository

### ISSUE THREAD

**Issue by 1technophile** [sui77/rc-switch#304]
I'm an heavy user of rcswitch through my project :  [OpenMQTTGateway](https://github.com/1technophile/OpenMQTTGateway)

I'm currently using a fork of the library : 
https://github.com/1technophile/rc-switch

But I would prefer to help the original repository instead of a fork.

Do you think I could have write access to the repo so as to help checking PR and merging them ?

**Comment by 1technophile** [comment]
@sui77 hello, what is your opinion about this proposal ?

**Comment by sui77** [comment]
Looks like contrary to me you are currently really involved into this stuff :) so yeah, cool.

**Comment by 1technophile** [comment]
Thanks perfect!
