### ISSUE TITLE
one sender with esp8266 to three receiver with attiny45

### ISSUE THREAD

**Issue by geekboy12** [sui77/rc-switch#31]
hi 
i want to send code with esp8266 like [this project ](http://www.instructables.com/id/ESP8266-12-standalone-blynk-control-outlets-wirele/) but i don't want use outlet , i want receive code with attiny45 and control just LED , with three node of tiny45 
my question is what is sketch for tiny45 
can someone help me ?

**Comment by fingolfin** [comment]
Sorry, we can't help with such specific questions. I recommend asking on a discussion forum for Arduino and / or esp8266
