### ISSUE TITLE
PR Travis CI is failing for unknown reason

### ISSUE THREAD

**Issue by to-scho** [sui77/rc-switch#314]
This is about PR "Fix and support for Conrad_RS-200 protocol #313". Travis system is stating about missing Ethernet.h. A have not touched corresponding code. Do I oversee something?

...
Building in release mode
305Compiling .pio/build/diecimilaatmega328/src/Webserver.ino.cpp.o
306Compiling .pio/build/diecimilaatmega328/libb61/rc-switch/RCSwitch.cpp.o
307/tmp/tmpPPPeSP/src/Webserver.ino:8:22: fatal error: Ethernet.h: No such file or directory
...

**Comment by 1technophile** [comment]
Should be ok now
