### ISSUE TITLE
Outdated Arduino library

### ISSUE THREAD

**Issue by dan-it** [sui77/rc-switch#317]
I'm really not sure if this issue belongs here, feel free to close if appropriate.

The official Arduino library (latest IDE -> _Tools_ -> _Manage libraries_ -> **rc-switch**) installs versions 2.6.2, taken from here downloads.arduino.cc/libraries/github.com/sui77/rc_switch-2.6.2.zip.
This file is missing the latest merges (learned because I ran into #139).

Hope this helps.

**Comment by 1technophile** [comment]
Yes, maybe it is time to release a 2.6.3

**Comment by 1technophile** [comment]
In all the case thanks for pointing that, #139  remember me this issue https://github.com/1technophile/OpenMQTTGateway/issues/337
And makes a plausible explanation.

**Comment by 1technophile** [comment]
done
