### ISSUE TITLE
The github version contain 12  protocol, instead the downloadable only 7

### ISSUE THREAD

**Issue by usane1** [sui77/rc-switch#334]
Hi!
The github version shows 12  protocol in cpp file, however, if i click on the latest version download and open, that only contain 7 protocol. Which is the actual version and is there other (major) differencies?

**Comment by 1technophile** [comment]
The difference is 5 protocols  : -)
The downloadable one is the last release, the master correspond to "in progress" work with less maturity.

**Comment by usane1** [comment]
Ok. Thank you.
