### ISSUE TITLE
Wrong sync bit position while sending

### ISSUE THREAD

**Issue by sleepwalkera** [sui77/rc-switch#354]
![image](https://user-images.githubusercontent.com/1573639/86510107-76865480-be1f-11ea-8e3d-cbe73c5dff12.png)
The sync bit should be at the beginning of the signal, but in the actual transmitted signal, the sync bit appears at the end of the signal. Tried various bit lengths, protocol configurations, and repetition times, and the sync bits all appeared at the end of the signal. 
Does anyone else have the same situation? Or am I missing something?

**Comment by sleepwalkera** [comment]
Have fixed in openmqttgateway version, closed.

**Comment by rob-deutsch** [comment]
I have noticed this too. I don't understand why this is the case. Does anyone have any insight?
