### ISSUE TITLE
how to send a simple ( on off modulation ) in stream binary

### ISSUE THREAD

**Issue by juankr10s** [sui77/rc-switch#365]
hi community
i need send a simple on off serial binary stream
without protocols 
only on off in a time secuence 
is posible in rc-switch?

**Comment by juankr10s** [comment]
i try edit protocol : 

{ 300, {  1, 1 }, {  0,  1 }, {  1,  0 } },    // protocol 5
but bit "0" is 96us more long than "1"
![Screenshot_20201010_225656](https://user-images.githubusercontent.com/45793359/95668548-ece7d080-0b4b-11eb-9e67-df66fb9b3e24.png)

**Comment by zoneamick** [comment]
as a simple question do you use a 315mhz transmitter?

**Comment by juankr10s** [comment]
hi
no, 434Mhz (rf module 433mhz)

**Comment by 1technophile** [comment]
> without protocols

It is not possible without a protocol, the protocol defines the signal modulation and demodulation.

But you can stick with protocol 1 and consider a decimal value 1234567 as ON and a decimal value 7654321 as OFF.

**Comment by juankr10s** [comment]
mmm ok
i think in a loop with delay (ms) on off gpio port for rf 433 module
well
thank you

**Comment by 1technophile** [comment]
There is also other protocols that support ON OFF like the one below:
https://github.com/sui77/rc-switch/blob/master/examples/TypeA_WithDIPSwitches/TypeA_WithDIPSwitches.ino if you don't want to reinvent the wheel.

> i think in a loop with delay (ms) on off gpio port for rf 433 module

Be careful about not jamming the 433mhz frequency
