### ISSUE TITLE
I can not use both frequency

### ISSUE THREAD

**Issue by nimaltd** [sui77/rc-switch#422]
How can I use both 315/433 frequency at the same time on 2 different pins.
```
RCSwitch                            rf433 = RCSwitch();
RCSwitch                            rf315 = RCSwitch();
.
.
.
void setup()
{
    rf315.enableReceive(6);
    rf433.enableReceive(7);
}
```
it does not work if I enabled both of them

**Comment by pierzogad** [comment]
Short answer is NO. 

RCSwitch implementation doesn't allow you to create 2 instances of code. There is just single (shared) variable for receiving buffer, return code and few others.
