### ISSUE TITLE
rc-switch not working on  Arduino YUN 

### ISSUE THREAD

**Issue by bjkellett** [sui77/rc-switch#43]
there have been a few posts and  thread going on arduino with this problem.  Direct link to the referenced thread  https://forum.arduino.cc/index.php?topic=274668.0

Something with the interrupt I guess.   Any ideas out there?

**Comment by fingolfin** [comment]
Without access to a Yun, there is nothing we can do to help debug this. I am afraid it is up to people who own a Yun to figure out a solution.

Of course if it turns out changes to rc-switch are needed, we'd be happy to make them resp. accept a pull request.
