### ISSUE TITLE
Problem detecting a single frame,  sync start condition. 

### ISSUE THREAD

**Issue by WoodsterDK** [sui77/rc-switch#50]
Hi I have used the transmit function to learn a copy remote some values. It seems the receive part only works if multiple values are sent (long press on my remote makes it retransmit ) . Could there be something with an issue getting in sync.

**Comment by fingolfin** [comment]
I think the receive code requires the signal to be transmitted twice before it accepts it. Not sure why, but you could try changing the line which says `if (repeatCount == 2)` to simply `if (true)` -- does that help?

@sui77 Any reason why the code waits for two full transmissions before accepting the signal?

**Comment by fingolfin** [comment]
Note that for my switches, no matter how short I press, I get at least two full repetitions of the signal. For another remote, it's even never below 5 repetitions.

**Comment by rotv** [comment]
I assume it's just to avoid false matches. My remotes also sends the code multiple times.

**Comment by WoodsterDK** [comment]
Ok, Will try it.
