### ISSUE TITLE
Add more boards to Travis CI tests

### ISSUE THREAD

**Issue by bau-sec** [sui77/rc-switch#64]
Once #61 is resolved, the boards that have specific conditional code (#ifdefs) for support should be added to the Travis CI tests. Right now that looks to be an ESP8266 based board and the Raspberry Pi.  

It wouldn't hurt to add more, but the two above are important to ensure the code compiles for all the platforms it aims to support.

**Comment by 1technophile** [comment]
Currently 9 boards are tested on CI
