### ISSUE TITLE
Why limited to certain transmitters?

### ISSUE THREAD

**Issue by TheConsciousness** [sui77/rc-switch#74]
When using the VirtualWire library, I can pick up any 433mhz transmitter (well, all of mine. Tested with 17 devices) However, when using this library it appears to be specifically designed to ignore all but the predefined transmitters, which only includes 2 of my own. Is this library specifically limited to ignore transmitters?

**Comment by fingolfin** [comment]
I am sorry but I don't quite understand what you are saying here. I am not sure what you mean with "predefined transmitters" ? All rc-switch asks for when transmitting is the pin to which the 433Mhz transmitter is attached. So all "normal" transmitters should work out of the box.

Perhaps you have some kind of alternate 433Mhz transmitter that requires a more complex protocol, like I2C or SPI?
