### ISSUE TITLE
ReceiveDemo_Simple not able to receive data

### ISSUE THREAD

**Issue by chirag7691** [sui77/rc-switch#81]
Hello,
I am using **ninjablocks/433Utils library which is use sui77/rc-switch library** for RF communication between raspberry pi 3 and Arduino Nano board using  433.92MHz Transmitter + Receiver [http://robokits.co.in/wireless-solutions/simple-rf-module/rf-super-regenerative-module-433mhz-transmitter-receiver]

I have setup transmitter on Arduino Nano board and receiver on raspberry Pi 3 board. I have used **"SendDemo.ino"** on Arduino Nano and **"RFSniffer.cpp"** on raspberry Pi 3. I have successfully received code sent by SendDemo but range is very law approx 1 meter only.

After that I have setup receiver on Arduino Nano board and transmitter on raspberry Pi 3 board. I have used **"codesend.cpp"** for sending code from raspberry pi and **"ReceiveDemo_Simple.ino"** for receiving code on Arduino board. I am not able to receive anything.

I also tried **"RF_Sniffer.ino"** from 433Utils library but same result. No output.
please help me to solve this problem.

**Comment by fingolfin** [comment]
Low range (1m is definitely not normal) might be a case of your antenna not being good enough.

As to the rest, without looking at your code, and knowing more details, it is impossible to say what might be wrong. In addition, it seems you are not using this "official" version, but rather a forked version maintained by ninjablocks/433Utils, so I think they would be in a better position to help you. So I recommend asking there -- and I would recommend reading http://www.catb.org/esr/faqs/smart-questions.html first :-)
