### ISSUE TITLE
Transmitter Left Open

### ISSUE THREAD

**Issue by jamestutton** [sui77/rc-switch#94]
Had a few occasions where the transmitter pin seems to be left in a High or floating state after certain transmissions effectively jamming the channel.   Can I suggest at the end of send function an explicit 

digitalWrite(this->nTransmitterPin, LOW);

Cant see any reason this should break anything else and should clear the channel for other users.

**Comment by roidayan** [comment]
Sounds like a good suggestion. In inverted signal like protocol 6 the last state is high and left like this if I'm not mistaken?

**Comment by roidayan** [comment]
Maybe you should make a pull request
